pipeline {
    agent any

    environment {
        PROJECT_DIR = "Django Example"
        VENV_DIR = "venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    sh """
                        rm -rf project
                        git clone https://github.com/vasantibendre06/POC2-Python-Web-App.git project
                    """
                }
            }
        }

        stage('Setup Python Environment') {
            steps {
                script {
                    sh """
                        cd "project/Django Example"
                        python3 -m venv ${VENV_DIR}
                        source ${VENV_DIR}/bin/activate && pip install --upgrade pip
                        source ${VENV_DIR}/bin/activate && pip install -r requirements.txt
                    """
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh """
                        cd "project/Django Example"
                        source ${VENV_DIR}/bin/activate && python manage.py test
                    """
                }
            }
        }

        stage('Deploy Django App') {
            steps {
                script {
                    sh """
                        cd "project/Django Example"
                        source ${VENV_DIR}/bin/activate && python manage.py migrate
                        source ${VENV_DIR}/bin/activate && python manage.py collectstatic --noinput
                        nohup python manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline execution completed."
        }
        success {
            echo "Build and Deployment Successful!"
        }
        failure {
            echo "Build or Deployment Failed."
        }
    }
}

